"""
Calculate the electric field of solid circle of charge.
"""

from typing import List

import numpy as np

# pylint: disable=import-error
from equations.base_charge import BaseCharge
from equations.constants import COULOMB_CONSTANT
# pylint: enable=import-error


class CircleCharge(BaseCharge):
    """
    A single circle of charge, with a position, radius, and a charge density.
    """

    def __init__(self, center: List[float], radius: float, charge_density: float) -> None:
        self.center = center
        self.radius = radius
        self.charge_density = charge_density

    def electric_field_magnitude(self, point: List[float]) -> float:
        """
        The net magnitude of the electric field at the given point.

        Args:
            point (List[float]): The point to measure the field at in the form ``[x, y]``.

        Returns:
            float: The net (signed) magnitude of the electric field at the given point, or zero if
            the magnitude is infinite.
        """

        # For simplicity, shift coordinates to have the center of the charge at the origin.
        relative_pos = self._relative_pos(point)

        radial_dist: float = np.sqrt(relative_pos[0]**2 + relative_pos[1]**2)
        cum_charge_rad = min(radial_dist, self.radius)

        charge_enc = np.pi * cum_charge_rad**2 * self.charge_density

        # E = k * q_enc / r^2
        return COULOMB_CONSTANT * charge_enc / radial_dist**2

    def electric_field_x(self, point: List[float]) -> float:
        """
        Calculate the x component of the magnetic field generated by the charge at a given point.

        Args:
            point (List[float]): test point to check.

        Returns:
            float: x component of electric field.
        """

        # The direction of the electric field is in the r direction. Get the angle of the shifted
        # coordinates, and take the cos of that.
        return self.electric_field_magnitude(point) * np.cos(self._theta(point))

    def electric_field_y(self, point: List[float]) -> float:
        """
        Calculate the y component of the magnetic field generated by the charge at a given point.

        Args:
            point (List[float]): test point to check.

        Returns:
            float: y component of electric field.
        """

        # The direction of the electric field is in the r direction. Get the angle of the shifted
        # coordinates, and take the sin of that.
        return self.electric_field_magnitude(point) * np.sin(self._theta(point))

    def _relative_pos(self, point: List[float]) -> List[float]:
        """
        Shifted coordinates with ``self.center`` at the origin.

        Args:
            point (List[float]): The point to get the offset from in the form ``[x, y]``.

        Returns:
            The offset coordinates in the form ``[x, y]``.
        """

        return [point[0] - self.center[0], point[1] - self.center[1]]

    def _theta(self, point: List[float]) -> float:
        """
        Get the angle between ``point`` and ``self.center``.
        """

        x_dist, y_dist = self._relative_pos(point)

        return np.arctan2(y_dist, x_dist)
